/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MakeReservation;

/**
 *
 * @author uks160030
 */
public class MinoaUI extends javax.swing.JFrame {
    Controller controller;

    /**
     * Creates new form MinoaUI
     */
    public MinoaUI() {
        initComponents();
        custDetPanel.setVisible(false);
        cardDetPanel.setVisible(false);
        controller = new Controller();
        searchButton.setVisible(false);
        saveCard.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startDateText = new javax.swing.JFormattedTextField();
        endDateText = new javax.swing.JFormattedTextField();
        availButton = new javax.swing.JButton();
        prepaidButton = new javax.swing.JButton();
        advButton = new javax.swing.JButton();
        convButton = new javax.swing.JButton();
        incentButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        custDetPanel = new javax.swing.JPanel();
        submitCust = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        custNameText = new javax.swing.JTextField();
        phoneNoText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        cardDetPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        submitCard = new javax.swing.JButton();
        cardNameText = new javax.swing.JTextField();
        carNoText = new javax.swing.JTextField();
        expiryText = new javax.swing.JTextField();
        saveCard = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();
        confirmChargesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Minoa Reservation System");

        jLabel2.setText("Start Date");

        jLabel3.setText("End Date");

        startDateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        endDateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        availButton.setText("Check Availability");
        availButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availButtonActionPerformed(evt);
            }
        });

        prepaidButton.setText("Prepaid Reservation");
        prepaidButton.setEnabled(false);
        prepaidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepaidButtonActionPerformed(evt);
            }
        });

        advButton.setText("60 Days Adv Res");
        advButton.setEnabled(false);
        advButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advButtonActionPerformed(evt);
            }
        });

        convButton.setText("Conventional Res");
        convButton.setEnabled(false);
        convButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convButtonActionPerformed(evt);
            }
        });

        incentButton.setText("Incentive Res");
        incentButton.setEnabled(false);
        incentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incentButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.setEnabled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        custDetPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        submitCust.setText("Submit");
        submitCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCustActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Phone No.");

        jLabel6.setText("Email");

        phoneNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Details");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout custDetPanelLayout = new javax.swing.GroupLayout(custDetPanel);
        custDetPanel.setLayout(custDetPanelLayout);
        custDetPanelLayout.setHorizontalGroup(
            custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custDetPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(custDetPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(custDetPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(custDetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(custNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(custDetPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(submitCust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
        custDetPanelLayout.setVerticalGroup(
            custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custDetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(custNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(custDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCust)
                    .addComponent(searchButton))
                .addContainerGap())
        );

        cardDetPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Name");

        jLabel9.setText("Card No");

        jLabel10.setText("Expiry");

        jLabel11.setText("Card Details");

        submitCard.setText("Charge");
        submitCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCardActionPerformed(evt);
            }
        });

        saveCard.setText("Save");
        saveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardDetPanelLayout = new javax.swing.GroupLayout(cardDetPanel);
        cardDetPanel.setLayout(cardDetPanelLayout);
        cardDetPanelLayout.setHorizontalGroup(
            cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDetPanelLayout.createSequentialGroup()
                .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardDetPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel11))
                    .addGroup(cardDetPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(cardDetPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(submitCard)
                .addGap(18, 18, 18)
                .addComponent(saveCard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardDetPanelLayout.setVerticalGroup(
            cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDetPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cardNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(carNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(expiryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(cardDetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCard)
                    .addComponent(saveCard))
                .addContainerGap())
        );

        jLabel13.setText("Total Cost: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Existing Reservation ?");

        paymentButton.setText("Make Payment");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmChargesButton.setText("Confirm Charges");
        confirmChargesButton.setEnabled(false);
        confirmChargesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChargesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(custDetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cardDetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(prepaidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(advButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(38, 38, 38)
                                            .addComponent(startDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(availButton)
                                                .addComponent(endDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(convButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(incentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel13)
                            .addGap(150, 150, 150)
                            .addComponent(totalCostLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(confirmChargesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(startDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(endDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(availButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prepaidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardDetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custDetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(confirmChargesButton)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(jButton7)
                    .addComponent(jLabel13)
                    .addComponent(totalCostLabel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>                        
    private void paymentScenario(){
    	controller.initPayment(startDateText.getText(), endDateText.getText());
        confirmChargesButton.setEnabled(true);
        cardDetPanel.setVisible(true);
        saveCard.setVisible(false);
    }
    private void submitCustActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String name = custNameText.getText();
        String phone = phoneNoText.getText();
        String email = emailText.getText();
        custDetPanel.setVisible(false);
        float cost = controller.enterGuestDetails(name, email, phone);
        totalCostLabel.setText(""+cost);
        int rt = controller.paymentNeeded(); 
        if(rt == 1){
           this.paymentScenario(); 
        }
        else if(rt == 3 || rt == 4){
            cardDetPanel.setVisible(true);
            submitCard.setVisible(false);
            saveCard.setVisible(true);
        }
        else{
        	confirmButton.setEnabled(true);
        }
    }                                          

    private void phoneNoTextActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void submitCardActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String cardname = cardNameText.getText();
        String cardno = carNoText.getText();
        String expiry = expiryText.getText();
        controller.enterCreditCard(cardname, cardno, expiry);
        if(controller.processPayment()){
            confirmButton.setEnabled(true);
        }
    }                                          

    private void prepaidButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String startDate = startDateText.getText();
        String endDate = endDateText.getText();
        controller.initPrepaid(startDate, endDate);
    }                                             

    private void advButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String startDate = startDateText.getText();
        String endDate = endDateText.getText();
        controller.init60DayAdv(startDate, endDate);
    }                                         

    private void convButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String startDate = startDateText.getText();
        String endDate = endDateText.getText();
        controller.initConventional(startDate, endDate);
    }                                          

    private void incentButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String startDate = startDateText.getText();
        String endDate = endDateText.getText();
        controller.initIncentive(startDate, endDate);
    }                                            

    private void availButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String startDate = startDateText.getText();
        String endDate = endDateText.getText();
        int daysrem = controller.checkAvailability(startDate, endDate);
        custDetPanel.setVisible(true);
        if(daysrem >= 0){
            convButton.setEnabled(true);
            if(daysrem <= 30)
            incentButton.setEnabled(true);
            if(daysrem >= 60){
                advButton.setEnabled(true);
                if(daysrem >= 90)
                    prepaidButton.setEnabled(true);
            }     
        }
    }                                           

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false); 
        this.dispose();
    }                                        

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        controller.confirmReservation();
        jLabel1.setText("Reservation Confirmed");
    }                                             

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        controller.initPayment(startDateText.getText(), endDateText.getText());
        custDetPanel.setVisible(true);
        submitCust.setVisible(false);
        searchButton.setVisible(true);
    }                                             

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
       String name = custNameText.getText();
       String phone = phoneNoText.getText();
       String email = emailText.getText();
       custDetPanel.setVisible(false);
       int charges = controller.searchRecord(name, phone, email);
       if(charges >= 0){
           totalCostLabel.setText(charges+"");
    	   this.paymentScenario();
       }
       else{
    	   totalCostLabel.setText("cust no found");
       }
       
    }                                            

    private void saveCardActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String cardname = cardNameText.getText();
        String cardno = carNoText.getText();
        String expiry = expiryText.getText();
        controller.enterCreditCard(cardname, cardno, expiry);
        confirmButton.setEnabled(true);
    }                                        

    private void confirmChargesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
         controller.confirmCharges();
    }                                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinoaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinoaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton advButton;
    private javax.swing.JButton availButton;
    private javax.swing.JTextField carNoText;
    private javax.swing.JPanel cardDetPanel;
    private javax.swing.JTextField cardNameText;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton confirmChargesButton;
    private javax.swing.JButton convButton;
    private javax.swing.JPanel custDetPanel;
    private javax.swing.JTextField custNameText;
    private javax.swing.JTextField emailText;
    private javax.swing.JFormattedTextField endDateText;
    private javax.swing.JTextField expiryText;
    private javax.swing.JButton incentButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton paymentButton;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JButton prepaidButton;
    private javax.swing.JButton saveCard;
    private javax.swing.JButton searchButton;
    private javax.swing.JFormattedTextField startDateText;
    private javax.swing.JButton submitCard;
    private javax.swing.JButton submitCust;
    private javax.swing.JLabel totalCostLabel;
    // End of variables declaration                   
}
